when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        tracing:
            enabled: '%env(bool:SENTRY_TRACING)%'
            dbal: # DB queries
                enabled: '%env(bool:SENTRY_TRACING)%'
            cache: # cache pools
                enabled: '%env(bool:SENTRY_TRACING)%'
            twig: # templating engine
                enabled: '%env(bool:SENTRY_TRACING)%'
            http_client: # Symfony HTTP client
                enabled: '%env(bool:SENTRY_TRACING)%'
        options:
            # Specify a fixed sample rate:
            traces_sample_rate: '%env(float:SENTRY_TRACING_SAMPLE_RATE)%'
